CREATE TABLE pomodoros
(
    id           UUID        NOT NULL,
    order_index  INTEGER     NOT NULL,
    completed    BOOLEAN     NOT NULL,
    session_type VARCHAR(20) NOT NULL,
    session_id   UUID        NOT NULL,
    CONSTRAINT pk_pomodoros PRIMARY KEY (id)
);

CREATE TABLE projects
(
    id          UUID         NOT NULL,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(1000),
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    owner_id    BIGINT       NOT NULL,
    CONSTRAINT pk_projects PRIMARY KEY (id)
);

CREATE TABLE session_configurations
(
    id                       UUID    NOT NULL,
    work_duration            INTEGER NOT NULL,
    short_break_duration     INTEGER NOT NULL,
    long_break_duration      INTEGER NOT NULL,
    cycles_before_long_break INTEGER NOT NULL,
    user_id                  BIGINT  NOT NULL,
    CONSTRAINT pk_session_configurations PRIMARY KEY (id)
);

CREATE TABLE session_tasks
(
    session_id UUID NOT NULL,
    task_id    UUID NOT NULL
);

CREATE TABLE sessions
(
    id                        UUID   NOT NULL,
    started_at                TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    ended_at                  TIMESTAMP WITHOUT TIME ZONE,
    work_minutes_used         time WITHOUT TIME ZONE,
    short_break_duration_used time WITHOUT TIME ZONE,
    long_break_duration_used  time WITHOUT TIME ZONE,
    user_id                   BIGINT NOT NULL,
    session_configuration_id  UUID,
    CONSTRAINT pk_sessions PRIMARY KEY (id)
);

CREATE TABLE tasks
(
    id             UUID         NOT NULL,
    title          VARCHAR(100) NOT NULL,
    description    VARCHAR(1000),
    archived       BOOLEAN      NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    completed_at   TIMESTAMP WITHOUT TIME ZONE,
    archived_at    TIMESTAMP WITHOUT TIME ZONE,
    owner_id       BIGINT       NOT NULL,
    parent_task_id UUID,
    status         VARCHAR(20)  NOT NULL,
    priority       VARCHAR(20)  NOT NULL,
    project_id     UUID,
    CONSTRAINT pk_tasks PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(50)                             NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    email      VARCHAR(100)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    enabled    BOOLEAN                                 NOT NULL,
    role       VARCHAR(20)                             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE session_configurations
    ADD CONSTRAINT uc_session_configurations_user UNIQUE (user_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE pomodoros
    ADD CONSTRAINT FK_POMODOROS_ON_SESSION FOREIGN KEY (session_id) REFERENCES sessions (id);

ALTER TABLE projects
    ADD CONSTRAINT FK_PROJECTS_ON_OWNER FOREIGN KEY (owner_id) REFERENCES users (id);

ALTER TABLE sessions
    ADD CONSTRAINT FK_SESSIONS_ON_SESSION_CONFIGURATION FOREIGN KEY (session_configuration_id) REFERENCES session_configurations (id);

ALTER TABLE sessions
    ADD CONSTRAINT FK_SESSIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE session_configurations
    ADD CONSTRAINT FK_SESSION_CONFIGURATIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE tasks
    ADD CONSTRAINT FK_TASKS_ON_OWNER FOREIGN KEY (owner_id) REFERENCES users (id);

ALTER TABLE tasks
    ADD CONSTRAINT FK_TASKS_ON_PARENT_TASK FOREIGN KEY (parent_task_id) REFERENCES tasks (id);

ALTER TABLE tasks
    ADD CONSTRAINT FK_TASKS_ON_PROJECT FOREIGN KEY (project_id) REFERENCES projects (id);

ALTER TABLE session_tasks
    ADD CONSTRAINT fk_sestas_on_session FOREIGN KEY (session_id) REFERENCES sessions (id);

ALTER TABLE session_tasks
    ADD CONSTRAINT fk_sestas_on_task FOREIGN KEY (task_id) REFERENCES tasks (id);