package com.jotomo.pomo.logging;

public enum AuditAction {
    TEST_HELLO,

    USER_REGISTERED,
    USER_LOGGED_IN,
    USER_LOGGED_OUT,

    TASK_CREATED,
    TASK_UPDATED,
    TASK_COMPLETED,
    TASK_ARCHIVED,
    TASK_DELETED,

    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_ARCHIVED,
    PROJECT_DELETED,

    SESSION_STARTED,
    SESSION_COMPLETED,
    SESSION_CANCELLED,

    CONFIGURATION_UPDATED
}